package com.mybook.app.mapper;

import com.mybook.app.model.WtInfo;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WtInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("id") String id, @Param("tId") String tId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_info
     *
     * @mbg.generated
     */
    int insert(WtInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_info
     *
     * @mbg.generated
     */
    WtInfo selectByPrimaryKey(@Param("id") String id, @Param("tId") String tId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_info
     *
     * @mbg.generated
     */
    List<WtInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WtInfo record);
}