package com.mybook.app.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class WtInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wt_info.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wt_info.t_id
     *
     * @mbg.generated
     */
    private String tId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wt_info.u_id
     *
     * @mbg.generated
     */
    private String uId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wt_info.value
     *
     * @mbg.generated
     */
    private BigDecimal value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wt_info.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wt_info.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wt_info.b_id
     *
     * @mbg.generated
     */
    private String bId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wt_info.o_id
     *
     * @mbg.generated
     */
    private String oId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wt_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wt_info.id
     *
     * @return the value of wt_info.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wt_info.id
     *
     * @param id the value for wt_info.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wt_info.t_id
     *
     * @return the value of wt_info.t_id
     *
     * @mbg.generated
     */
    public String gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wt_info.t_id
     *
     * @param tId the value for wt_info.t_id
     *
     * @mbg.generated
     */
    public void settId(String tId) {
        this.tId = tId == null ? null : tId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wt_info.u_id
     *
     * @return the value of wt_info.u_id
     *
     * @mbg.generated
     */
    public String getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wt_info.u_id
     *
     * @param uId the value for wt_info.u_id
     *
     * @mbg.generated
     */
    public void setuId(String uId) {
        this.uId = uId == null ? null : uId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wt_info.value
     *
     * @return the value of wt_info.value
     *
     * @mbg.generated
     */
    public BigDecimal getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wt_info.value
     *
     * @param value the value for wt_info.value
     *
     * @mbg.generated
     */
    public void setValue(BigDecimal value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wt_info.time
     *
     * @return the value of wt_info.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wt_info.time
     *
     * @param time the value for wt_info.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wt_info.type
     *
     * @return the value of wt_info.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wt_info.type
     *
     * @param type the value for wt_info.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wt_info.b_id
     *
     * @return the value of wt_info.b_id
     *
     * @mbg.generated
     */
    public String getbId() {
        return bId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wt_info.b_id
     *
     * @param bId the value for wt_info.b_id
     *
     * @mbg.generated
     */
    public void setbId(String bId) {
        this.bId = bId == null ? null : bId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wt_info.o_id
     *
     * @return the value of wt_info.o_id
     *
     * @mbg.generated
     */
    public String getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wt_info.o_id
     *
     * @param oId the value for wt_info.o_id
     *
     * @mbg.generated
     */
    public void setoId(String oId) {
        this.oId = oId == null ? null : oId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wt_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", tId=").append(tId);
        sb.append(", uId=").append(uId);
        sb.append(", value=").append(value);
        sb.append(", time=").append(time);
        sb.append(", type=").append(type);
        sb.append(", bId=").append(bId);
        sb.append(", oId=").append(oId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}